# Generated by Django 5.0.3 on 2025-03-19 11:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelfy', '0001_initial'),
        ('user_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLibrary',
            new_name='UserLibraryItem',
        ),
    ]
