# Generated by Django 5.0.3 on 2025-03-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_library', '0002_rename_userlibrary_userlibraryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibraryitem',
            name='progress_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
