# Generated by Django 5.0.3 on 2025-03-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_library', '0003_userlibraryitem_progress_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlibraryitem',
            old_name='progress_notes',
            new_name='notes',
        ),
    ]
