# Generated by Django 5.1.7 on 2025-03-30 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_library_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_library.userlibraryitem')),
            ],
        ),
    ]
