# Generated by Django 5.1.7 on 2025-03-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Charts',
        ),
    ]
