# Generated by Django 5.1.3 on 2025-04-10 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('game', 'Game')], max_length=10)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('studio', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('comment_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_comment_author', to='user_management.profile')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelfy.media')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
