# Generated by Django 5.0.3 on 2025-03-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('game', 'Game')], max_length=10)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('studio', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
